import type { DishTemplate } from "./types";

function item(
  name: string,
  qty: number,
  unit: string,
  aisle: string,
  unitCost: number,
  pantry?: boolean,
): DishTemplate["ingredients"][number] {
  return { name, qty, unit, aisle, unitCost, pantry };
}

export const DISH_CATALOG: DishTemplate[] = [
  {
    catalogId: "citrus-fennel-salad",
    course: "starter",
    name: "Citrus fennel salad",
    description: "Shaved fennel, orange, olive oil, and black pepper. Bright enough to open a winter table.",
    cuisine: "italian",
    diet: "vegan",
    allergens: [],
    tags: ["salad", "raw", "gluten-free"],
    costPerServing: 2.4,
    prepMinutes: 20,
    cookMinutes: 0,
    ingredients: [
      item("fennel bulbs", 0.35, "each", "produce", 1.1),
      item("oranges", 0.5, "each", "produce", 0.6),
      item("olive oil", 1, "tbsp", "pantry", 0.2, true),
      item("lemon", 0.25, "each", "produce", 0.15),
    ],
  },
  {
    catalogId: "white-bean-crostini",
    course: "starter",
    name: "White bean crostini",
    description: "Rosemary white beans on toasted country bread. Pass them standing up with something cold.",
    cuisine: "italian",
    diet: "vegan",
    allergens: ["gluten"],
    tags: ["bread", "beans"],
    costPerServing: 1.8,
    prepMinutes: 15,
    cookMinutes: 10,
    ingredients: [
      item("baguette", 0.15, "each", "bakery", 0.7),
      item("cannellini beans", 0.2, "can", "grocery", 0.4),
      item("garlic", 0.3, "clove", "produce", 0.05),
      item("rosemary", 0.5, "sprig", "produce", 0.15),
    ],
  },
  {
    catalogId: "cacio-e-pepe",
    course: "main",
    name: "Cacio e pepe",
    description: "Tonnarelli, pecorino, and a reckless amount of pepper. The pasta people came for.",
    cuisine: "italian",
    diet: "vegetarian",
    allergens: ["gluten", "dairy"],
    tags: ["pasta", "roman"],
    costPerServing: 3.6,
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      item("tonnarelli or spaghetti", 4, "oz", "grocery", 0.8),
      item("pecorino romano", 1.2, "oz", "dairy", 1.4),
      item("black pepper", 1, "tsp", "pantry", 0.05, true),
      item("butter", 0.3, "tbsp", "dairy", 0.1),
    ],
  },
  {
    catalogId: "mushroom-polenta",
    course: "main",
    name: "Mushroom ragu on polenta",
    description: "Brown mushrooms, thyme, and soft polenta. The vegan main that does not apologize.",
    cuisine: "italian",
    diet: "vegan",
    allergens: [],
    tags: ["gluten-free", "polenta", "comfort"],
    costPerServing: 4.2,
    prepMinutes: 20,
    cookMinutes: 35,
    ingredients: [
      item("mixed mushrooms", 5, "oz", "produce", 2.1),
      item("polenta", 2, "oz", "grocery", 0.4),
      item("shallots", 0.4, "each", "produce", 0.25),
      item("thyme", 1, "sprig", "produce", 0.1),
      item("vegetable stock", 0.5, "cup", "grocery", 0.3),
    ],
  },
  {
    catalogId: "herb-roast-chicken",
    course: "main",
    name: "Herb roast chicken",
    description: "Salted early, roasted on onions, finished with lemon. One bird for the omnivores.",
    cuisine: "italian",
    diet: "omnivore",
    allergens: [],
    tags: ["gluten-free", "roast"],
    costPerServing: 4.8,
    prepMinutes: 20,
    cookMinutes: 70,
    ingredients: [
      item("whole chicken", 0.2, "each", "butcher", 3.2),
      item("onions", 0.25, "each", "produce", 0.15),
      item("lemon", 0.25, "each", "produce", 0.15),
      item("olive oil", 1, "tbsp", "pantry", 0.2, true),
    ],
  },
  {
    catalogId: "chili-broccolini",
    course: "side",
    name: "Chili broccolini",
    description: "Charred stems, garlic, and a pinch of chile. Green on an otherwise beige plate.",
    cuisine: "italian",
    diet: "vegan",
    allergens: [],
    tags: ["green", "gluten-free"],
    costPerServing: 2.1,
    prepMinutes: 8,
    cookMinutes: 10,
    ingredients: [
      item("broccolini", 4, "oz", "produce", 1.5),
      item("garlic", 0.5, "clove", "produce", 0.05),
      item("chili flakes", 0.2, "tsp", "pantry", 0.02, true),
    ],
  },
  {
    catalogId: "olive-oil-cake",
    course: "dessert",
    name: "Olive oil cake",
    description: "A one-bowl cake that tastes like a Ligurian afternoon. No nuts, no frosting argument.",
    cuisine: "italian",
    diet: "vegetarian",
    allergens: ["eggs", "gluten", "dairy"],
    tags: ["cake"],
    costPerServing: 1.9,
    prepMinutes: 15,
    cookMinutes: 45,
    ingredients: [
      item("flour", 2, "oz", "pantry", 0.15, true),
      item("olive oil", 1.5, "tbsp", "pantry", 0.3, true),
      item("eggs", 0.4, "each", "dairy", 0.25),
      item("sugar", 1.5, "oz", "pantry", 0.1, true),
      item("orange zest", 0.2, "each", "produce", 0.2),
    ],
  },
  {
    catalogId: "blood-orange-spritz",
    course: "drink",
    name: "Blood orange spritz",
    description: "Bitter, cold, and not too sweet. The house drink that keeps people from arriving hungry.",
    cuisine: "italian",
    diet: "vegan",
    allergens: [],
    tags: ["aperitivo", "gluten-free"],
    costPerServing: 2.8,
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      item("blood orange juice", 3, "oz", "produce", 0.8),
      item("sparkling water", 3, "oz", "grocery", 0.3),
      item("bitter aperitif", 1.5, "oz", "liquor", 1.4),
    ],
  },
  {
    catalogId: "gf-lemon-risotto",
    course: "main",
    name: "Lemon risotto",
    description: "Carnaroli, zest, and a little mascarpone. The gluten-free stand-in when pasta is off the table.",
    cuisine: "italian",
    diet: "vegetarian",
    allergens: ["dairy"],
    tags: ["gluten-free", "rice"],
    costPerServing: 3.9,
    prepMinutes: 15,
    cookMinutes: 30,
    ingredients: [
      item("arborio rice", 3, "oz", "grocery", 0.7),
      item("parmesan", 0.8, "oz", "dairy", 0.9),
      item("lemon", 0.4, "each", "produce", 0.2),
      item("vegetable stock", 1, "cup", "grocery", 0.4),
    ],
  },
  {
    catalogId: "hummus-crudite",
    course: "starter",
    name: "Hummus and crudités",
    description: "Tahini-heavy hummus, cold vegetables, and olive oil. People eat more than they admit.",
    cuisine: "mediterranean",
    diet: "vegan",
    allergens: ["sesame"],
    tags: ["dip", "gluten-free"],
    costPerServing: 1.7,
    prepMinutes: 20,
    cookMinutes: 0,
    ingredients: [
      item("chickpeas", 0.25, "can", "grocery", 0.3),
      item("tahini", 1, "tbsp", "grocery", 0.35),
      item("cucumbers", 0.25, "each", "produce", 0.3),
      item("carrots", 0.4, "each", "produce", 0.2),
    ],
  },
  {
    catalogId: "chickpea-stew",
    course: "main",
    name: "Tomato chickpea stew",
    description: "Slow tomatoes, cumin, and a pile of herbs. A vegan main that scales without drama.",
    cuisine: "mediterranean",
    diet: "vegan",
    allergens: [],
    tags: ["gluten-free", "stew"],
    costPerServing: 3.2,
    prepMinutes: 15,
    cookMinutes: 40,
    ingredients: [
      item("chickpeas", 0.4, "can", "grocery", 0.5),
      item("canned tomatoes", 0.35, "can", "grocery", 0.4),
      item("onions", 0.25, "each", "produce", 0.15),
      item("cumin", 0.5, "tsp", "pantry", 0.05, true),
    ],
  },
  {
    catalogId: "lemon-roast-fish",
    course: "main",
    name: "Lemon herb roast fish",
    description: "A side of hake or cod, roasted on fennel. For the pescatarians and anyone tired of chicken.",
    cuisine: "mediterranean",
    diet: "pescatarian",
    allergens: ["fish"],
    tags: ["gluten-free", "roast"],
    costPerServing: 6.4,
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      item("white fish fillet", 5, "oz", "fish", 4.8),
      item("fennel bulbs", 0.2, "each", "produce", 0.6),
      item("lemon", 0.3, "each", "produce", 0.15),
    ],
  },
  {
    catalogId: "fattoush",
    course: "side",
    name: "Fattoush",
    description: "Torn bread, sumac, and whatever crunchy vegetables survived the week.",
    cuisine: "mediterranean",
    diet: "vegan",
    allergens: ["gluten"],
    tags: ["salad"],
    costPerServing: 2.2,
    prepMinutes: 20,
    cookMinutes: 5,
    ingredients: [
      item("pita", 0.4, "each", "bakery", 0.5),
      item("romaine", 0.25, "head", "produce", 0.5),
      item("sumac", 0.4, "tsp", "pantry", 0.08, true),
      item("tomatoes", 0.4, "each", "produce", 0.4),
    ],
  },
  {
    catalogId: "orange-yogurt",
    course: "dessert",
    name: "Orange blossom yogurt",
    description: "Thick yogurt, honey, and orange blossom. Ten minutes, no oven politics.",
    cuisine: "mediterranean",
    diet: "vegetarian",
    allergens: ["dairy"],
    tags: ["gluten-free", "no-bake"],
    costPerServing: 1.6,
    prepMinutes: 10,
    cookMinutes: 0,
    ingredients: [
      item("greek yogurt", 4, "oz", "dairy", 0.8),
      item("honey", 1, "tsp", "pantry", 0.15, true),
      item("orange blossom water", 0.2, "tsp", "grocery", 0.1),
    ],
  },
  {
    catalogId: "elote-cups",
    course: "starter",
    name: "Elote cups",
    description: "Charred corn, lime, and chile in a cup you can hold while talking.",
    cuisine: "mexican",
    diet: "vegetarian",
    allergens: ["dairy"],
    tags: ["corn", "street"],
    costPerServing: 1.9,
    prepMinutes: 15,
    cookMinutes: 10,
    ingredients: [
      item("corn kernels", 0.4, "cup", "produce", 0.6),
      item("cotija", 0.4, "oz", "dairy", 0.4),
      item("lime", 0.3, "each", "produce", 0.15),
      item("chili powder", 0.3, "tsp", "pantry", 0.03, true),
    ],
  },
  {
    catalogId: "jackfruit-tacos",
    course: "main",
    name: "Jackfruit tacos",
    description: "Braised jackfruit, pickled onion, and salsa verde. The vegan main that disappears first.",
    cuisine: "mexican",
    diet: "vegan",
    allergens: ["gluten"],
    tags: ["tacos"],
    costPerServing: 3.4,
    prepMinutes: 20,
    cookMinutes: 30,
    ingredients: [
      item("young jackfruit", 0.35, "can", "grocery", 1.2),
      item("corn tortillas", 2, "each", "grocery", 0.4),
      item("red onion", 0.15, "each", "produce", 0.1),
      item("tomatillos", 1.5, "each", "produce", 0.4),
    ],
  },
  {
    catalogId: "chicken-tinga",
    course: "main",
    name: "Chicken tinga",
    description: "Shredded chicken in chipotle tomato. Make it in the afternoon and stop thinking about it.",
    cuisine: "mexican",
    diet: "omnivore",
    allergens: [],
    tags: ["braise", "gluten-free"],
    costPerServing: 3.8,
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      item("chicken thighs", 4, "oz", "butcher", 1.8),
      item("chipotle in adobo", 0.4, "each", "grocery", 0.3),
      item("tomatoes", 0.5, "each", "produce", 0.4),
      item("onion", 0.2, "each", "produce", 0.1),
    ],
  },
  {
    catalogId: "agua-fresca",
    course: "drink",
    name: "Hibiscus agua fresca",
    description: "Cold jamaica, a little sugar, and lime. Non-alcoholic on purpose.",
    cuisine: "mexican",
    diet: "vegan",
    allergens: [],
    tags: ["gluten-free", "agua"],
    costPerServing: 0.9,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      item("dried hibiscus", 0.3, "oz", "grocery", 0.35),
      item("lime", 0.25, "each", "produce", 0.12),
      item("sugar", 0.4, "oz", "pantry", 0.05, true),
    ],
  },
  {
    catalogId: "chana-masala",
    course: "main",
    name: "Chana masala",
    description: "Chickpeas in a tomato-ginger gravy. The pot you can leave on the back burner.",
    cuisine: "indian",
    diet: "vegan",
    allergens: [],
    tags: ["gluten-free", "stew"],
    costPerServing: 2.6,
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      item("chickpeas", 0.4, "can", "grocery", 0.5),
      item("onion", 0.3, "each", "produce", 0.15),
      item("ginger", 0.3, "inch", "produce", 0.1),
      item("garam masala", 0.5, "tsp", "pantry", 0.08, true),
      item("canned tomatoes", 0.3, "can", "grocery", 0.35),
    ],
  },
  {
    catalogId: "chicken-tikka",
    course: "main",
    name: "Chicken tikka",
    description: "Yogurt-marinated, roasted hot. Serve with the chana and stop plating individually.",
    cuisine: "indian",
    diet: "omnivore",
    allergens: ["dairy"],
    tags: ["grill"],
    costPerServing: 4.5,
    prepMinutes: 25,
    cookMinutes: 25,
    ingredients: [
      item("chicken thighs", 5, "oz", "butcher", 2.2),
      item("yogurt", 2, "oz", "dairy", 0.3),
      item("tikka masala", 1, "tsp", "pantry", 0.1, true),
      item("lemon", 0.2, "each", "produce", 0.1),
    ],
  },
  {
    catalogId: "cucumber-raita",
    course: "side",
    name: "Cucumber raita",
    description: "Cold yogurt, cucumber, and toasted cumin. The table needs this more than another hot dish.",
    cuisine: "indian",
    diet: "vegetarian",
    allergens: ["dairy"],
    tags: ["gluten-free", "cool"],
    costPerServing: 1.1,
    prepMinutes: 10,
    cookMinutes: 0,
    ingredients: [
      item("yogurt", 3, "oz", "dairy", 0.4),
      item("cucumber", 0.2, "each", "produce", 0.25),
      item("cumin", 0.3, "tsp", "pantry", 0.03, true),
    ],
  },
  {
    catalogId: "mango-lassi",
    course: "drink",
    name: "Mango lassi",
    description: "Mango, yogurt, a pinch of cardamom. Dessert pretending to be a drink.",
    cuisine: "indian",
    diet: "vegetarian",
    allergens: ["dairy"],
    tags: ["drink"],
    costPerServing: 1.8,
    prepMinutes: 8,
    cookMinutes: 0,
    ingredients: [
      item("mango pulp", 3, "oz", "grocery", 0.7),
      item("yogurt", 3, "oz", "dairy", 0.4),
      item("cardamom", 1, "pinch", "pantry", 0.02, true),
    ],
  },
  {
    catalogId: "miso-soup",
    course: "starter",
    name: "Miso soup",
    description: "Dashi, tofu, and scallion. Quiet, hot, and done in twelve minutes.",
    cuisine: "japanese",
    diet: "vegan",
    allergens: ["soy"],
    tags: ["soup", "gluten-free"],
    costPerServing: 1.4,
    prepMinutes: 8,
    cookMinutes: 12,
    ingredients: [
      item("white miso", 1, "tbsp", "grocery", 0.3),
      item("soft tofu", 2, "oz", "produce", 0.4),
      item("scallions", 0.3, "each", "produce", 0.1),
      item("wakame", 0.5, "tsp", "grocery", 0.1),
    ],
  },
  {
    catalogId: "tofu-dengaku",
    course: "main",
    name: "Miso-glazed tofu",
    description: "Broiled tofu with a sweet miso lacquer. The vegan main that looks like you tried.",
    cuisine: "japanese",
    diet: "vegan",
    allergens: ["soy"],
    tags: ["gluten-free"],
    costPerServing: 2.9,
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      item("firm tofu", 5, "oz", "produce", 1.4),
      item("white miso", 1, "tbsp", "grocery", 0.3),
      item("mirin", 1, "tsp", "grocery", 0.15),
      item("scallions", 0.2, "each", "produce", 0.08),
    ],
  },
  {
    catalogId: "miso-salmon",
    course: "main",
    name: "Miso salmon",
    description: "The same glaze as the tofu, on salmon. Two pans, one idea.",
    cuisine: "japanese",
    diet: "pescatarian",
    allergens: ["fish", "soy"],
    tags: ["gluten-free"],
    costPerServing: 7.2,
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      item("salmon fillet", 5, "oz", "fish", 5.5),
      item("white miso", 1, "tbsp", "grocery", 0.3),
      item("mirin", 1, "tsp", "grocery", 0.15),
    ],
  },
];

export const CUISINES = [
  "italian",
  "mediterranean",
  "mexican",
  "indian",
  "japanese",
] as const;

export function findDishTemplates(query: string): DishTemplate[] {
  const q = query.toLowerCase();
  return DISH_CATALOG.filter((dish) => {
    return (
      dish.name.toLowerCase().includes(q) ||
      dish.catalogId.includes(q) ||
      dish.tags.some((tag) => tag.includes(q)) ||
      dish.course === q ||
      dish.cuisine === q
    );
  });
}

export function getDishByCatalogId(catalogId: string): DishTemplate | undefined {
  return DISH_CATALOG.find((dish) => dish.catalogId === catalogId);
}
